# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqI9GSV_2vB8EqJJn7tTUhV0TQYtsO2G
"""

from model import predict_crop
from crop_analysis import get_analysis

