# -*- coding: utf-8 -*-
"""crop_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgR7OB8dgIara3F8kW05WY50KC-6m8q3
"""



!pip install earthengine-api geemap

import ee
import geemap

ee.Authenticate()

ee.Initialize(project='cropai-isro-hackathon')

print(ee.Number(10).getInfo())

Map = geemap.Map()

Map

Map.add_draw_control()

Map

roi = Map.user_roi

roi

area = roi.area(maxError=1).divide(4047)

print("Farm Area:", area.getInfo(), "acres")

print(roi)

collection = (
    ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
    .filterBounds(roi)
    .filterDate("2025-06-01","2025-10-01")
    .filter(ee.Filter.lt("CLOUDY_PIXEL_PERCENTAGE",20))
)

image = collection.median().clip(roi)

image

Map.addLayer(
    image,
    {
        'bands':['B4','B3','B2'],
        'min':0,
        'max':3000
    },
    "Satellite Image"
)

Map

ndvi = image.normalizedDifference(
    ['B8','B4']
).rename("NDVI")


Map.addLayer(
    ndvi,
    {
        'min':0,
        'max':1,
        'palette':['red','yellow','green']
    },
    "Crop Health"
)

Map

ndvi_value = ndvi.reduceRegion(
    reducer=ee.Reducer.mean(),
    geometry=roi,
    scale=10
)

print(ndvi_value.getInfo())

value = ndvi_value.getInfo()['NDVI']


if value < 0.3:
    status="Poor Crop Health 🔴"

elif value < 0.6:
    status="Moderate Crop Health 🟡"

else:
    status="Healthy Crop 🟢"


print(status)

ndwi = image.normalizedDifference(
    ['B3','B8']
).rename("NDWI")


Map.addLayer(
    ndwi,
    {
        'min':-1,
        'max':1,
        'palette':['brown','white','blue']
    },
    "Water Status"
)

Map

ndwi_value = ndwi.reduceRegion(
    reducer=ee.Reducer.mean(),
    geometry=roi,
    scale=10,
    maxPixels=1e9
)

print(ndwi_value.getInfo())
water = ndwi_value.getInfo()['NDWI']

print(water)

water = ndwi_value.getInfo()['NDWI']

if water < -0.2:
    print("Water stress detected ⚠️")
    print("Recommendation: Irrigation required")

elif water < 0:
    print("Low moisture")
    print("Recommendation: Monitor irrigation")

else:
    print("Good moisture condition ✅")

report = {
    "Farm Area(acres)": area.getInfo(),
    "NDVI": value,
    "Crop Status": status,
    "NDWI": water
}

report

landsat = (
    ee.ImageCollection("LANDSAT/LC08/C02/T1_L2")
    .filterBounds(roi)
    .filterDate("2025-06-01","2025-10-01")
    .median()
)

temperature = (
    landsat.select("ST_B10")
    .multiply(0.00341802)
    .add(149)
    .clip(roi)
)

Map.addLayer(
    temperature,
    {
        'min':20,
        'max':50,
        'palette':['blue','yellow','red']
    },
    "Temperature"
)

Map

temp_value = temperature.reduceRegion(
    reducer=ee.Reducer.mean(),
    geometry=roi,
    scale=30,
    maxPixels=1e9
)

temp = temp_value.getInfo()

temp

temp_c = list(temp.values())[0]

if temp_c > 40:
    heat_status = "High Heat Stress 🔴"
    heat_advice = "Irrigation recommended"

elif temp_c > 30:
    heat_status = "Moderate Heat 🟡"
    heat_advice = "Monitor crop"

else:
    heat_status = "Normal Temperature 🟢"
    heat_advice = "No heat stress"


print(heat_status)
print(heat_advice)

final_report = {

"Farm Area (acre)": area.getInfo(),

"Crop Health": status,

"NDVI": value,

"Water Status": water,

"Temperature": temp_c,

"Heat Condition": heat_status,

"Recommendation": heat_advice

}

final_report





import pandas as pd
import numpy as np

"""dummy dataset"""

data = {
    "NDVI":[0.2,0.35,0.5,0.65,0.8,0.9],
    "NDWI":[-0.3,-0.1,0,0.2,0.4,0.5],
    "Temperature":[45,40,35,30,28,25],
    "Health":[
        "Poor",
        "Poor",
        "Medium",
        "Medium",
        "Healthy",
        "Healthy"
    ]
}


df = pd.DataFrame(data)

df

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Health"] = encoder.fit_transform(df["Health"])

df

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


X = df[
    ["NDVI","NDWI","Temperature"]
]

y = df["Health"]


X_train,X_test,y_train,y_test = train_test_split(
    X,y,
    test_size=0.3,
    random_state=42
)


model = RandomForestClassifier(
    n_estimators=100
)

model.fit(
    X_train,
    y_train
)

print("Model trained")

accuracy = model.score(
    X_test,
    y_test
)

accuracy

farmer_data = pd.DataFrame({
    "NDVI":[value],
    "NDWI":[water],
    "Temperature":[temp_c]
})


prediction = model.predict(
    farmer_data
)


result = encoder.inverse_transform(
    prediction
)


print("Predicted Crop Health:", result[0])



