# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b70KgdO-p9YQKtCo3PoSQLNZpGfJ0f14
"""

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder


# training function
def create_model():

    np.random.seed(42)

    n = 200

    ndvi = np.random.uniform(0,1,n)
    ndwi = np.random.uniform(-0.5,0.5,n)
    temp = np.random.uniform(20,50,n)

    health=[]

    for i in range(n):

        if ndvi[i] > 0.6 and temp[i] < 35:
            health.append("Healthy")

        elif ndvi[i] > 0.35:
            health.append("Medium")

        else:
            health.append("Poor")


    df = pd.DataFrame({
        "NDVI":ndvi,
        "NDWI":ndwi,
        "Temperature":temp,
        "Health":health
    })


    encoder = LabelEncoder()

    df["Health"] = encoder.fit_transform(df["Health"])


    X=df[["NDVI","NDWI","Temperature"]]
    y=df["Health"]


    model = RandomForestClassifier(
        n_estimators=100,
        random_state=42
    )


    model.fit(X,y)


    return model,encoder



# prediction function
def predict_crop(ndvi, ndwi, temp):

    model,encoder = create_model()


    sample = pd.DataFrame({
        "NDVI":[ndvi],
        "NDWI":[ndwi],
        "Temperature":[temp]
    })


    pred = model.predict(sample)


    return encoder.inverse_transform(pred)[0]

from model import predict_crop

predict_crop(0.7,0.1,30)

